### ISSUE TITLE
Collections are not accepted as input in a workflow

### ISSUE THREAD

**Issue by TKlingstrom** [SGBC/galaksio#31]
After importing a history using Galaxy I was unable to use the collections in it as input parameters in my workflow. The collections showed up correctly in the history view but when selecting input they were unavailable in the dropdown menu. They were  available when selecting "browse collections" but "use selected" did not allow me to select them as input datasets. After cancelling the workflow and trying again they were available in the dropdown menus.

**Comment by fikipollo** [comment]
Yes, that was because if you skip the step 2 (history selection) and go to step 3 (input data selection), then go back to step 2 and change your history and go to step 3, the dropdowns for choosing the input data do not change so the collections in the selected history are not available.
I've forced to recreate the dropdowns when going back to step 2 however this option invalidates the previous selection in step 3 (whether you change or not the history).

**Comment by TKlingstrom** [comment]
Nice, now it works as it should, the input file list however still only show "-- Choose a file"
 after a collection have been selected even if the square around it turns green. Having the file name being displayed would help so people remember what they have done.

**Comment by TKlingstrom** [comment]
Nice, now it works as it should, the input file list however still only show "-- Choose a file"
 after a collection have been selected even if the square around it turns green. Having the file name being displayed would help so people remember what they have done.

**Comment by fikipollo** [comment]
You are not working yet on the latest version :tongue:
